import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
from project.lookup import cred

def create_playlist(name):
    sp = spotipy.Spotify(auth='BQBZRbR2ehzPlMSEPE_faJ2h7_nXtDT66ojZbYC6Tu9jQ9l0rgBi7n62iFlvjKCAZpIDSOnTKDXS6enGqV5dS7hnOJIAgCUpcCCGrQZux6bhwa79GUcgUy8HmzsGvI_m05XAnOcvlCAOdfvBLkxgZWSpNCecv8tJE6SqjtEik_oahhVEBPlDht9DRNXM5BtgJRHoRfBd_GDYLNqp9tLytC3qgmXXK5vj9cOdUDLXOBA5')
    return sp.user_playlist_create(cred.client_username, name)

def add_to_playlist(playlist_id, songs):
    sp = spotipy.Spotify(auth='BQBZRbR2ehzPlMSEPE_faJ2h7_nXtDT66ojZbYC6Tu9jQ9l0rgBi7n62iFlvjKCAZpIDSOnTKDXS6enGqV5dS7hnOJIAgCUpcCCGrQZux6bhwa79GUcgUy8HmzsGvI_m05XAnOcvlCAOdfvBLkxgZWSpNCecv8tJE6SqjtEik_oahhVEBPlDht9DRNXM5BtgJRHoRfBd_GDYLNqp9tLytC3qgmXXK5vj9cOdUDLXOBA5')
    sp.user_playlist_add_tracks(cred.client_username, playlist_id, songs)
