"""reset db

Revision ID: 6b6a30fb954e
Revises: 
Create Date: 2018-06-26 17:17:48.386752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6a30fb954e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('song',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('artist', sa.String(length=100), nullable=True),
    sa.Column('spotify_url', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.String(length=10), nullable=True),
    sa.Column('suggest_list_id', sa.String(length=11), nullable=True),
    sa.Column('gen_list_id', sa.String(length=11), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_room_last_used'), 'room', ['last_used'], unique=False)
    op.create_index(op.f('ix_room_room_id'), 'room', ['room_id'], unique=True)
    op.create_table('auth_users',
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.String(length=11), nullable=True),
    sa.Column('room', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['room'], ['room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('song_lists',
    sa.Column('list_id', sa.Integer(), nullable=True),
    sa.Column('song_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['list_id'], ['list.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('song_lists')
    op.drop_table('list')
    op.drop_table('auth_users')
    op.drop_index(op.f('ix_room_room_id'), table_name='room')
    op.drop_index(op.f('ix_room_last_used'), table_name='room')
    op.drop_table('room')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('song')
    # ### end Alembic commands ###
